package com.listamercado.interfazgrafica;

import com.listamercado.conexiondb.Conexion;
import com.listamercado.establecerimagen.*;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author JONATHAN
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal() {
        initComponents();
        //Conexion.getConnection();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarProductos();
    }

    //Establecer el tamaño
    public static String rutaImagen = null;
    int pos = 0;
    //

    public boolean verificarCampos() {
        if (txt_nombre.getText() == null || txt_precio.getText() == null
                || txt_AddFecha.getDate() == null) {
            return false;
        } else {
            try {
                Float.parseFloat(txt_precio.getText());
                return true;
            } catch (Exception e) {
                return false;
            }
        }
    }
    
    //Crear arraylist para llenar la tabla
    public ArrayList<Producto> getProductList(){
        ArrayList<Producto> listaProducto = new ArrayList<Producto>();
        try{
            Connection cn = Conexion.getConnection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM productos");
            Producto producto;
            
            while(rs.next()){
                producto = new Producto(rs.getInt("id"), rs.getString("nombre"), Float.parseFloat(rs.getString("precio")), 
                        rs.getString("add_fecha"), rs.getBytes("imagen"));
                listaProducto.add(producto);
            }
            
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
        return listaProducto;
    }
    
    //Llenar la tabla con el arraylist creado
    public void mostrarProductos(){
        ArrayList<Producto> lista = getProductList();
        DefaultTableModel modelo = (DefaultTableModel)Tabla_Productos.getModel();
        //limpiar la tabla
        modelo.setRowCount(0);
        Object[] row = new Object[4];
        
        for(int i = 0; i < lista.size(); i++){
            row[0] = lista.get(i).getId();
            row[1] = lista.get(i).getNombre();
            row[2] = lista.get(i).getPrecio();
            row[3] = lista.get(i).getAddFecha();
            
            modelo.addRow(row);
        }
                
    }
    
    public void mostrarItem(int index){
        txt_id.setText(Integer.toString(getProductList().get(index).getId()));
        txt_nombre.setText(getProductList().get(index).getNombre());
        txt_precio.setText(Float.toString(getProductList().get(index).getPrecio()));
        try{
        Date addDate = null;
        addDate = new SimpleDateFormat("yyyy-MM-dd").parse((String)getProductList().get(index).getAddFecha());
        txt_AddFecha.setDate(addDate);
        }catch(ParseException e){
            e.printStackTrace();
        }
        label_imagen.setIcon(Tamaño.EstablecerTamaño(null, getProductList().get(index).getImagen()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_AddFecha = new com.toedter.calendar.JDateChooser();
        txt_nombre = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        label_imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Productos = new javax.swing.JTable();
        boton_Elegir_Imagen = new javax.swing.JButton();
        Boton_Insertar = new javax.swing.JButton();
        Boton_Actualizar = new javax.swing.JButton();
        Boton_Eliminar = new javax.swing.JButton();
        b_Siguiente = new javax.swing.JButton();
        b_Primero = new javax.swing.JButton();
        b_Ultimo = new javax.swing.JButton();
        b_Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio:");

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Imagen:");

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setPreferredSize(new java.awt.Dimension(59, 49));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_AddFecha.setDateFormatString("yyyy-MM-dd");
        txt_AddFecha.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setPreferredSize(new java.awt.Dimension(59, 49));
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txt_precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_precio.setPreferredSize(new java.awt.Dimension(59, 49));
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });

        label_imagen.setBackground(new java.awt.Color(255, 102, 102));
        label_imagen.setOpaque(true);

        Tabla_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio", "Fecha"
            }
        ));
        Tabla_Productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_ProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Productos);

        boton_Elegir_Imagen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        boton_Elegir_Imagen.setText("Elegir Imagen");
        boton_Elegir_Imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Elegir_ImagenActionPerformed(evt);
            }
        });

        Boton_Insertar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/listamercado/images/add-1.png"))); // NOI18N
        Boton_Insertar.setText(" Insertar");
        Boton_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_InsertarActionPerformed(evt);
            }
        });

        Boton_Actualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/listamercado/images/upd-1.png"))); // NOI18N
        Boton_Actualizar.setText("Actualizar");
        Boton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_ActualizarActionPerformed(evt);
            }
        });

        Boton_Eliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/listamercado/images/del-1.png"))); // NOI18N
        Boton_Eliminar.setText("Eliminar");
        Boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EliminarActionPerformed(evt);
            }
        });

        b_Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_Siguiente.setText(">");
        b_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SiguienteActionPerformed(evt);
            }
        });

        b_Primero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_Primero.setText("|<- ");
        b_Primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_PrimeroActionPerformed(evt);
            }
        });

        b_Ultimo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_Ultimo.setText("->|");
        b_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UltimoActionPerformed(evt);
            }
        });

        b_Atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_Atras.setText("<");
        b_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Boton_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_Elegir_Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_AddFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Boton_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_Primero, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(b_Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(b_Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_AddFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_Elegir_Imagen))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Insertar)
                    .addComponent(b_Siguiente)
                    .addComponent(b_Atras)
                    .addComponent(b_Ultimo)
                    .addComponent(b_Primero)
                    .addComponent(Boton_Actualizar)
                    .addComponent(Boton_Eliminar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void Boton_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_InsertarActionPerformed

        if (verificarCampos() && rutaImagen != null) {
            try {
                Connection cn = Conexion.getConnection();
                //System.out.println("**"+txt_nombre.getText() +"**"+ txt_precio.getText() +"**"+ rutaImagen);
                PreparedStatement pst = cn.prepareStatement("INSERT INTO productos(nombre,precio,add_fecha,imagen) VALUES(?,?,?,?)");
                //pst.setString(1, "");
                pst.setString(1, txt_nombre.getText());
                pst.setString(2, txt_precio.getText());

                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                String addFecha = formatoFecha.format(txt_AddFecha.getDate());
                pst.setString(3, addFecha);

                InputStream img = new FileInputStream(new File(rutaImagen));
                pst.setBlob(4, img);
                pst.executeUpdate();
                
                mostrarProductos();
                JOptionPane.showMessageDialog(null, "Dato ingresado");

            } catch (HeadlessException | FileNotFoundException | SQLException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor completa los campos");
        }
    }//GEN-LAST:event_Boton_InsertarActionPerformed

    private void Boton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_ActualizarActionPerformed
        if (verificarCampos() && txt_id.getText() != null) {

            Connection cn = Conexion.getConnection();
            if (rutaImagen == null) {
                try {
                    PreparedStatement pst = cn.prepareStatement("UPDATE productos SET nombre = ?, precio= ?,"
                            + "add_fecha = ? WHERE id = ?");
                    pst.setString(1, txt_nombre.getText());
                    pst.setString(2, txt_precio.getText());

                    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                    String addFecha = formatoFecha.format(txt_AddFecha.getDate());
                    pst.setString(3, addFecha);

                    pst.setInt(4, Integer.parseInt(txt_id.getText()));
                    pst.executeUpdate();
                    
                    mostrarProductos();
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                } catch (HeadlessException | SQLException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    PreparedStatement pst = cn.prepareStatement("UPDATE productos SET nombre = ?, precio= ?,"
                            + "add_fecha = ?, imagen = ? WHERE id = ?");
                    pst.setString(1, txt_nombre.getText());
                    pst.setString(2, txt_precio.getText());

                    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                    String addFecha = formatoFecha.format(txt_AddFecha.getDate());
                    pst.setString(3, addFecha);

                    InputStream img = new FileInputStream(new File(rutaImagen));
                    pst.setBlob(4, img);

                    pst.setString(5, txt_id.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
                } catch (FileNotFoundException | SQLException e) {
                    e.printStackTrace();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"Algunos campos estan vacios.");
        }
    }//GEN-LAST:event_Boton_ActualizarActionPerformed

    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        if(!txt_id.getText().equals("")){
            try {
                Connection cn = Conexion.getConnection();
                PreparedStatement pst = cn.prepareStatement("DELETE FROM productos WHERE id = ?");
                
                pst.setInt(1, Integer.parseInt(txt_id.getText()));
                pst.executeUpdate();
                mostrarProductos();
                JOptionPane.showMessageDialog(null, "Registro Eliminado");
            } catch (HeadlessException | NumberFormatException | SQLException e) {
                e.printStackTrace();
        }
        }else{
            JOptionPane.showMessageDialog(null,"Ingresa una ID");
        }
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    private void b_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SiguienteActionPerformed
        pos++;
        if(pos >= getProductList().size()){
            pos = getProductList().size()-1;
            
        }
        mostrarItem(pos);
    }//GEN-LAST:event_b_SiguienteActionPerformed

    private void b_PrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_PrimeroActionPerformed
        pos = 0;
        mostrarItem(pos);
    }//GEN-LAST:event_b_PrimeroActionPerformed

    private void b_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UltimoActionPerformed
        pos = getProductList().size()-1;
        mostrarItem(pos);
    }//GEN-LAST:event_b_UltimoActionPerformed

    private void b_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AtrasActionPerformed
        pos--;
        if(pos < 0){
            pos = 0;
            
        }
        mostrarItem(pos);
    }//GEN-LAST:event_b_AtrasActionPerformed

    private void boton_Elegir_ImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Elegir_ImagenActionPerformed
        EleccionImagen ei = new EleccionImagen();
        ei.elegirImagen();

    }//GEN-LAST:event_boton_Elegir_ImagenActionPerformed

    private void Tabla_ProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_ProductosMouseClicked
        int index = Tabla_Productos.getSelectedRow();
        mostrarItem(index);
    }//GEN-LAST:event_Tabla_ProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Actualizar;
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JButton Boton_Insertar;
    private javax.swing.JTable Tabla_Productos;
    private javax.swing.JButton b_Atras;
    private javax.swing.JButton b_Primero;
    private javax.swing.JButton b_Siguiente;
    private javax.swing.JButton b_Ultimo;
    private javax.swing.JButton boton_Elegir_Imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel label_imagen;
    private com.toedter.calendar.JDateChooser txt_AddFecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
